kind: Deployment
apiVersion: apps/v1
metadata: 
  name: netflix-deployment
  labels:
    app: netflix
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: netflix

  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix-container
          image: 
          ports:
            - containerPort: 3000  
